[build]
  base = "."
  command = "npm ci --prefix apps/web-next && npm --prefix apps/web-next test && npm --prefix apps/web-next run build"
  publish = "apps/web-next/.next"

[build.environment]
  NODE_VERSION = "22.22.0"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"

[images]
  remote_images = [
    "http://hakusasonso\\.jp/.*",
    "http://snowcontemporary\\.com/.*",
    "http://www\\.hakusasonso\\.jp/.*",
    "http://www\\.snowcontemporary\\.com/.*",
    "https://10chancerylanegallery\\.com/.*",
    "https://13anewstreet\\.com/.*",
    "https://2121designsight\\.jp/.*",
    "https://a-c-k\\.jp/.*",
    "https://aaa\\.org\\.hk/.*",
    "https://aham\\.jp/.*",
    "https://apo\\.hk/.*",
    "https://art-view\\.roppongihills\\.com/.*",
    "https://art\\.andspace\\.net/.*",
    "https://art\\.parco\\.jp/.*",
    "https://art16\\.net/.*",
    "https://artcourtgallery\\.com/.*",
    "https://artizon\\.museum/.*",
    "https://artm\\.pref\\.hyogo\\.jp/.*",
    "https://artosaka\\.jp/.*",
    "https://artro\\.jp/.*",
    "https://arts-science\\.com/.*",
    "https://asahigroup-oyamazaki\\.com/.*",
    "https://asiasociety\\.org/.*",
    "https://atelier\\.muji\\.com/.*",
    "https://atz-image\\.s3\\.ap-northeast-1\\.amazonaws\\.com/.*",
    "https://baiken\\.jp/.*",
    "https://baseec-img-mng\\.akamaized\\.net/.*",
    "https://benbrownfinearts\\.com/.*",
    "https://blindspotgallery\\.com/.*",
    "https://blogger\\.googleusercontent\\.com/.*",
    "https://bluelotus-gallery\\.com/.*",
    "https://bunpaku\\.or\\.jp/.*",
    "https://cbal\\.com\\.hk/.*",
    "https://cdn\\.sanity\\.io/.*",
    "https://cdn\\.shopify\\.com/.*",
    "https://chushin\\.co\\.jp/.*",
    "https://curation-fair\\.com/.*",
    "https://davidzwirner\\.com/.*",
    "https://dnpfcp\\.jp/.*",
    "https://emptygallery\\.com/.*",
    "https://emuseum\\.or\\.jp/.*",
    "https://en\\.art\\.parco\\.jp/.*",
    "https://en\\.gyre-omotesando\\.com/.*",
    "https://fukuda-art-museum\\.jp/.*",
    "https://gagosian\\.com/.*",
    "https://galeriedumonde\\.com/.*",
    "https://gallery-kitano\\.com/.*",
    "https://gallery-taketwo\\.com/.*",
    "https://gallery-yamahon\\.com/.*",
    "https://gallery\\.hkas\\.edu\\.hk/.*",
    "https://gallery\\.kcua\\.ac\\.jp/.*",
    "https://galleryexit\\.com/.*",
    "https://gallerymorningkyoto\\.blogspot\\.com/.*",
    "https://gallerymorningkyoto\\.com/.*",
    "https://galleryunfold\\.com/.*",
    "https://grottofineart\\.com/.*",
    "https://gyre-omotesando\\.com/.*",
    "https://hakari\\.art/.*",
    "https://hanart\\.com/.*",
    "https://hankyu-bunka\\.or\\.jp/.*",
    "https://hilltoposaka\\.com/.*",
    "https://hitoto\\.info/.*",
    "https://hkac\\.org\\.hk/.*",
    "https://hkdi\\.edu\\.hk/.*",
    "https://hkpm\\.org\\.hk/.*",
    "https://hokusai-museum\\.jp/.*",
    "https://hosoogallery\\.jp/.*",
    "https://huko\\.jp/.*",
    "https://i\\.ytimg\\.com/.*",
    "https://ichion-contemporary\\.com/.*",
    "https://igallery-osaka\\.com/.*",
    "https://image\\.jimcdn\\.com/.*",
    "https://images\\.microcms-assets\\.io/.*",
    "https://images\\.squarespace-cdn\\.com/.*",
    "https://imuraart\\.com/.*",
    "https://isseymiyake\\.com/.*",
    "https://jitsuzaisei\\.com/.*",
    "https://jpsgallery\\.com/.*",
    "https://kac\\.or\\.jp/.*",
    "https://kankakari\\.com/.*",
    "https://kenjitaki\\.com/.*",
    "https://kiangmalingue\\.com/.*",
    "https://kinutani-tenku\\.jp/.*",
    "https://koenkyoto\\.theshop\\.jp/.*",
    "https://kojin-kyoto\\.com/.*",
    "https://kosetsu-museum\\.or\\.jp/.*",
    "https://kouichifinearts\\.com/.*",
    "https://kuramonzen\\.com/.*",
    "https://kusakabeg\\.com/.*",
    "https://kwaifunghin\\.com/.*",
    "https://kyohaku\\.go\\.jp/.*",
    "https://kyoto-art-month\\.jp/.*",
    "https://kyoto-ba\\.jp/.*",
    "https://kyoto\\.theterminal\\.jp/.*",
    "https://kyotocity-kyocera\\.museum/.*",
    "https://kyotographie\\.jp/.*",
    "https://kyotophonie\\.jp/.*",
    "https://leica-camera\\.com/.*",
    "https://lurfgallery\\.com/.*",
    "https://lurfmuseum\\.art/.*",
    "https://mahokubota\\.com/.*",
    "https://masaki-art-museum\\.jp/.*",
    "https://miho\\.jp/.*",
    "https://mill6chat\\.org/.*",
    "https://mingeikan-osaka\\.or\\.jp/.*",
    "https://mingeikan\\.or\\.jp/.*",
    "https://momak\\.go\\.jp/.*",
    "https://momat\\.go\\.jp/.*",
    "https://mori\\.art\\.museum/.*",
    "https://mot-art-museum\\.jp/.*",
    "https://mplus\\.org\\.hk/.*",
    "https://mtkcontemporaryart\\.com/.*",
    "https://museum\\.geidai\\.ac\\.jp/.*",
    "https://nact\\.jp/.*",
    "https://nakka-art\\.jp/.*",
    "https://nanzuka\\.com/.*",
    "https://newpureplus\\.com/.*",
    "https://nmao\\.go\\.jp/.*",
    "https://nomart\\.co\\.jp/.*",
    "https://nonaka-hill\\.com/.*",
    "https://oneaspace\\.org\\.hk/.*",
    "https://operacity\\.jp/.*",
    "https://ora-ora\\.com/.*",
    "https://osaka-geidai\\.ac\\.jp/.*",
    "https://osaka-ukiyoe-museum\\.com/.*",
    "https://osaka\\.congres-square\\.jp/.*",
    "https://oscaarmouligne\\.com/.*",
    "https://otafinearts\\.com/.*",
    "https://para-site\\.art/.*",
    "https://perrotin\\.com/.*",
    "https://play2020\\.jp/.*",
    "https://plus-y-gallery\\.com/.*",
    "https://pmq\\.org\\.hk/.*",
    "https://po-holdings\\.co\\.jp/.*",
    "https://purple-purple\\.com/.*",
    "https://raku-yaki\\.or\\.jp/.*",
    "https://rossirossi\\.com/.*",
    "https://samac\\.jp/.*",
    "https://scaithebathhouse\\.com/.*",
    "https://sen-oku\\.or\\.jp/.*",
    "https://setagayaartmuseum\\.or\\.jp/.*",
    "https://shop\\.lurfgallery\\.com/.*",
    "https://sibasi\\.jp/.*",
    "https://sinsinfineart\\.com/.*",
    "https://sokyogallery\\.com/.*",
    "https://solunafineart\\.com/.*",
    "https://standingpine\\.jp/.*",
    "https://standingpine\\.storage\\.googleapis\\.com/.*",
    "https://static-assets\\.artlogic\\.net/.*",
    "https://static\\.wixstatic\\.com/.*",
    "https://static1\\.squarespace\\.com/.*",
    "https://storage\\.googleapis\\.com/.*",
    "https://suchsize\\.com/.*",
    "https://takaishiigallery\\.com/.*",
    "https://takeninagawa\\.com/.*",
    "https://takeo\\.co\\.jp/.*",
    "https://taro-okamoto\\.or\\.jp/.*",
    "https://taronasugallery\\.com/.*",
    "https://tcv\\.roppongihills\\.com/.*",
    "https://tezukayama-g\\.com/.*",
    "https://tobikan\\.jp/.*",
    "https://tokyonode\\.jp/.*",
    "https://topmuseum\\.jp/.*",
    "https://videotage\\.org\\.hk/.*",
    "https://villepinart\\.com/.*",
    "https://wa-gallery\\.art/.*",
    "https://what\\.warehouseofart\\.org/.*",
    "https://white-cube\\.transforms\\.svdcdn\\.com/.*",
    "https://whitecube\\.com/.*",
    "https://whitestone-gallery\\.com/.*",
    "https://www\\.10chancerylanegallery\\.com/.*",
    "https://www\\.13anewstreet\\.com/.*",
    "https://www\\.2121designsight\\.jp/.*",
    "https://www\\.aham\\.jp/.*",
    "https://www\\.apo\\.hk/.*",
    "https://www\\.art16\\.net/.*",
    "https://www\\.artcourtgallery\\.com/.*",
    "https://www\\.artizon\\.museum/.*",
    "https://www\\.artm\\.pref\\.hyogo\\.jp/.*",
    "https://www\\.artosaka\\.jp/.*",
    "https://www\\.asahigroup-oyamazaki\\.com/.*",
    "https://www\\.benbrownfinearts\\.com/.*",
    "https://www\\.bunpaku\\.or\\.jp/.*",
    "https://www\\.cbal\\.com\\.hk/.*",
    "https://www\\.chushin\\.co\\.jp/.*",
    "https://www\\.davidzwirner\\.com/.*",
    "https://www\\.dnpfcp\\.jp/.*",
    "https://www\\.emuseum\\.or\\.jp/.*",
    "https://www\\.galeriedumonde\\.com/.*",
    "https://www\\.gallery-kitano\\.com/.*",
    "https://www\\.gallery-taketwo\\.com/.*",
    "https://www\\.galleryexit\\.com/.*",
    "https://www\\.grottofineart\\.com/.*",
    "https://www\\.hanart\\.com/.*",
    "https://www\\.hankyu-bunka\\.or\\.jp/.*",
    "https://www\\.hilltoposaka\\.com/.*",
    "https://www\\.hkac\\.org\\.hk/.*",
    "https://www\\.hkdi\\.edu\\.hk/.*",
    "https://www\\.hkpm\\.org\\.hk/.*",
    "https://www\\.hosoogallery\\.jp/.*",
    "https://www\\.ichion-contemporary\\.com/.*",
    "https://www\\.igallery-osaka\\.com/.*",
    "https://www\\.imuraart\\.com/.*",
    "https://www\\.isseymiyake\\.com/.*",
    "https://www\\.jitsuzaisei\\.com/.*",
    "https://www\\.jpsgallery\\.com/.*",
    "https://www\\.kac\\.or\\.jp/.*",
    "https://www\\.kankakari\\.com/.*",
    "https://www\\.kenjitaki\\.com/.*",
    "https://www\\.kiangmalingue\\.com/.*",
    "https://www\\.kinutani-tenku\\.jp/.*",
    "https://www\\.kosetsu-museum\\.or\\.jp/.*",
    "https://www\\.kusakabeg\\.com/.*",
    "https://www\\.kwaifunghin\\.com/.*",
    "https://www\\.kyohaku\\.go\\.jp/.*",
    "https://www\\.kyotographie\\.jp/.*",
    "https://www\\.mahokubota\\.com/.*",
    "https://www\\.miho\\.jp/.*",
    "https://www\\.mill6chat\\.org/.*",
    "https://www\\.mingeikan-osaka\\.or\\.jp/.*",
    "https://www\\.momak\\.go\\.jp/.*",
    "https://www\\.momat\\.go\\.jp/.*",
    "https://www\\.mori\\.art\\.museum/.*",
    "https://www\\.mot-art-museum\\.jp/.*",
    "https://www\\.mplus\\.org\\.hk/.*",
    "https://www\\.nact\\.jp/.*",
    "https://www\\.nmao\\.go\\.jp/.*",
    "https://www\\.nomart\\.co\\.jp/.*",
    "https://www\\.nonaka-hill\\.com/.*",
    "https://www\\.oneaspace\\.org\\.hk/.*",
    "https://www\\.operacity\\.jp/.*",
    "https://www\\.ora-ora\\.com/.*",
    "https://www\\.osaka-geidai\\.ac\\.jp/.*",
    "https://www\\.otafinearts\\.com/.*",
    "https://www\\.pacegallery\\.com/.*",
    "https://www\\.para-site\\.art/.*",
    "https://www\\.perrotin\\.com/.*",
    "https://www\\.plus-y-gallery\\.com/.*",
    "https://www\\.pmq\\.org\\.hk/.*",
    "https://www\\.po-holdings\\.co\\.jp/.*",
    "https://www\\.polamuseum\\.or\\.jp/.*",
    "https://www\\.raku-yaki\\.or\\.jp/.*",
    "https://www\\.rossirossi\\.com/.*",
    "https://www\\.samac\\.jp/.*",
    "https://www\\.scaithebathhouse\\.com/.*",
    "https://www\\.sen-oku\\.or\\.jp/.*",
    "https://www\\.setagayaartmuseum\\.or\\.jp/.*",
    "https://www\\.sinsinfineart\\.com/.*",
    "https://www\\.solunafineart\\.com/.*",
    "https://www\\.suchsize\\.com/.*",
    "https://www\\.takaishiigallery\\.com/.*",
    "https://www\\.takeninagawa\\.com/.*",
    "https://www\\.takeo\\.co\\.jp/.*",
    "https://www\\.takeopapershow\\.com/.*",
    "https://www\\.taronasugallery\\.com/.*",
    "https://www\\.tezukayama-g\\.com/.*",
    "https://www\\.tobikan\\.jp/.*",
    "https://www\\.tokyonode\\.jp/.*",
    "https://www\\.videotage\\.org\\.hk/.*",
    "https://www\\.villepinart\\.com/.*",
    "https://www\\.whitecube\\.com/.*",
    "https://www\\.whitestone-gallery\\.com/.*",
    "https://www\\.yamatane-museum\\.jp/.*",
    "https://www\\.yodgallery\\.com/.*",
    "https://www\\.yoshimiarts\\.com/.*",
    "https://www\\.yutakakikutakegallery\\.com/.*",
    "https://yamatane-museum\\.jp/.*",
    "https://yayoikusamamuseum\\.jp/.*",
    "https://yodgallery\\.com/.*",
    "https://yoshimiarts\\.com/.*",
    "https://yutakakikutakegallery\\.com/.*",
    "https://zenbi\\.kagizen\\.com/.*",
  ]

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self)"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
